import { StyleSheet } from 'react-native';
import Svg, { Rect, Defs, LinearGradient, Stop } from 'react-native-svg';
import { theme } from "../Colors";
import PieChart from 'react-native-pie-chart';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#ffffff",
    },
    header: {
        flexDirection: "row",
        paddingHorizontal: 20,
        alignItems: "center",
        marginHorizontal: 10,
        marginTop: 20,
        overflow: 'hidden',
        borderRadius: 20,
    },
    headerBg: {
        flex: 1,
        height: '100%',
        width: '100%', 
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    headerText: {
        fontSize: 30,
        fontWeight: "600",
        fontWeight: 200,
        textAlign: "center",
        marginHorizontal: 15,
        marginVertical: 5,
        color: theme.textColor,
    },
    screen: {
        height: "100%",
        marginHorizontal: 30,
        marginTop: -10,
        marginBottom: -10,
        borderRadius: 12,
        justifyContent: "flex-start",
    },
    verticalSeparator: {
        height: "90%",
        width: "5",
        backgroundColor: theme.folderColor,
        borderRadius: 15,
        justifyContent: "center",
        alignSelf: "center",
    },
    scrollContainer: {
        padding: 20,
        alignItems: "flex-start",
        paddingVertical: -10,
        paddingHorizontal: 20,
    },
    row: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "flex-start",
        marginVertical: 5,
    },
    modalContainer: {
        flex: 1,
        justifyContent: "flex-end"
    },
    modal: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        padding: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    modalItem: {
        backgroundColor: "#1A1C20",
        width: "50%",
        marginBottom: 10,
        paddingVertical: 20,
        paddingHorizontal: 20,
        borderRadius: 15,
        flexDirection: "row",
        alignItems: "center",
    },
    modalText: {
        color: theme.bg,
        fontSize: 15,
        marginHorizontal: 20,
    },
    modalscreen: {
        backgroundColor: theme.bg,
        width: "65%",
        marginBottom: 10,
        paddingTop: 30,
        paddingBottom: 50,
        paddingHorizontal: 10,
        borderRadius: 15,
        flexDirection: "column",
        alignItems: "center",
    },
    folderModalScreen: {
        backgroundColor: "#F1FAFF",
        width: "70%",
        paddingVertical: 20,
        paddingHorizontal: 5,
        marginBottom:10,
        borderRadius: 15,
        flexDirection: "column",
        alignItems: "center",
        justifyContent:"space-between"
    },
    PieChartContainer:{
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
        width: 300,
        height: 300,
    },
    pieChartText: {
        fontSize: "36",
        fontWeight: "100%",
        color: "#394C8B",
        textAlign: "center",
    },
    inputContainer: {
        width: "60%",
        alignItems: "flex-end",
        marginVertical: 70,
    },
    input: {
        backgroundColor: "#ffffff",
        borderColor: "#394C8B",
        borderWidth: 3,
        width: "80%",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 15,
        marginVertical: 10,
        //textAlign: "center",
        fontSize: 20,
    },
    changeNameinput: {
        backgroundColor: theme.screenBg,
        width: "90%",
        paddingVertical: 10,
        paddingHorizontal: 10,
        borderRadius: 15,
        marginVertical: 5,
        textAlign: "center",
        fontSize: 30,
    },
    Button: {
        backgroundColor: "#394C8B",
        paddingHorizontal: 45,
        paddingVertical: 15,
        //marginHorizontal: 5,
        marginVertical: 3,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
    },
    addButton: {
        borderRadius: "50%", 
        paddingHorizontal: 12,
        paddingVertical: 5,
        marginLeft: 10,
        marginVertical: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    closeButton: {
        backgroundColor: theme.wrongSign,
        width: "50%",
        marginBottom: 10,
        paddingVertical: 20,
        paddingHorizontal: 20,
        borderRadius: 15,
        flexDirection: "row",
        alignItems: "center",
    },
    tabButton: {
        paddingVertical:10,
        paddingHorizontal:40,
        marginHorizontal: 10,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
    },
    modalButton: {
        backgroundColor: theme.buttonColor,
        width: "90%",
        marginBottom: 5,
        paddingVertical: 10,
        paddingHorizontal: 10,
        borderRadius: 15,
        flexDirection: "row",
        justifyContent:"center",
        alignItems: "center",
    },
    Icon: {
        color: theme.iconColor,
        height: 120,
        weight: 120,
        padding: 10,
        marginHorizontal: 5,
        marginTop: -10,
        marginBottom: -10,
        justifyContent: "center",
        alignItems: "center",
    },
    addIcon: {
        color: theme.textColor,
        paddingVertical: 5,
        paddingHorizontal: 5,
        justifyContent: "center",
    },
    folderIcon: {
        color: theme.folderColor,
        paddingTop: 20,
        paddingHorizontal: 20,
        marginHorizontal: 10,
        marginVertical: 5,
        alignItems: "flex-start",
    },
    tabIcon: {
        color: theme.textColor,
        paddingVertical: 5,
        paddingHorizontal: 5,
        marginHorizontal: 5,
        marginVertical: 5,
        justifyContent: "center",
        alignItems: "center",
    },
    folderName: {
        color: theme.textColor,
        lineHeight: 20,
        marginRight: 3,
        fontSize: 20,
        textAlign: "center",
        fontWeight: 300,
    }
});

export default styles;

